# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: deepl-rb 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "deepl-rb"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Daniel Herzog"]
  s.date = "2018-01-04"
  s.description = "A simple ruby wrapper for the DeepL translation API (v1). For more information, check this: https://www.deepl.com/docs/api-reference.html"
  s.email = "info@danielherzog.es"
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md"
  ]
  s.files = [
    ".circleci/config.yml",
    ".rubocop.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.md",
    "README.md",
    "Rakefile",
    "VERSION",
    "deepl-rb.gemspec",
    "lib/deepl.rb",
    "lib/deepl/api.rb",
    "lib/deepl/configuration.rb",
    "lib/deepl/exceptions/authorization_failed.rb",
    "lib/deepl/exceptions/bad_request.rb",
    "lib/deepl/exceptions/error.rb",
    "lib/deepl/exceptions/limit_exceeded.rb",
    "lib/deepl/exceptions/request_error.rb",
    "lib/deepl/requests/base.rb",
    "lib/deepl/requests/translate_text.rb",
    "lib/deepl/resources/base.rb",
    "lib/deepl/resources/text.rb",
    "spec/api/api_spec.rb",
    "spec/api/configuration_spec.rb",
    "spec/api/deepl_spec.rb",
    "spec/fixtures/vcr_cassettes/deepl_translate.yml",
    "spec/fixtures/vcr_cassettes/translate_texts.yml",
    "spec/requests/translate_text_spec.rb",
    "spec/resources/text_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/wikiti/deepl-rb"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A simple ruby wrapper for the DeepL API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<juwelier>, [">= 0"])
    else
      s.add_dependency(%q<juwelier>, [">= 0"])
    end
  else
    s.add_dependency(%q<juwelier>, [">= 0"])
  end
end

